controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"


      min_vel_x: 0.0
      max_vel_x: 0.3
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_vel_theta: -1.0
      acc_lim_x: 2.5
      acc_lim_theta: 3.2

      vx_samples: 20
      vy_samples: 0
      vtheta_samples: 40

      sim_time: 2.0
      linear_granularity: 0.05
      angular_granularity: 0.025
      time_granularity: 0.025
      max_rot_vel: 1.0
      min_rot_vel: 0.2

      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: true

      critics: ["RotateToGoal", "GoalAlign", "PathAlign", "PathDist", "GoalDist", "ObstacleFootprint"]
      GoalAlign.scale: 24.0
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.325
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

